"""Constants and exit codes for rig."""

from __future__ import annotations

import re

RUNTIME_DIR_NAME = ".local-run"
__version__ = "1.0.4"
LOCK_FILE_NAME = "checkout.lock"
STATE_FILE_NAME = "state.json"
LOG_DIR_NAME = "logs"
DATA_DIR_NAME = "data"
DIR_MODE_PRIVATE = 0o700
FILE_MODE_PRIVATE = 0o600

LOCK_TIMEOUT_SECS = 10.0
HEALTH_TIMEOUT_SECS = 45.0
TEARDOWN_TIMEOUT_SECS = 5.0
PORT_RELEASE_TIMEOUT_SECS = 5.0
PORT_RETRY_ATTEMPTS = 3
PORT_MIN = 1
PORT_MAX = 65535
COMPOSE_UP_TIMEOUT_SECS = 180.0
COMPOSE_DISCOVERY_TIMEOUT_SECS = 60.0
COMPOSE_TEARDOWN_TIMEOUT_SECS = 30.0
DEFAULT_STARTUP_WAIT_SECS = 0.3

SERVICE_TYPES = ("fd", "port", "compose")
SCOPES = ("full", "local", "backend", "ui")

BASE_ENV_ALLOWLIST = (
    "PATH",
    "HOME",
    "USER",
    "LOGNAME",
    "SHELL",
    "TERM",
    "TMPDIR",
    "TZ",
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "SSL_CERT_FILE",
    "SSL_CERT_DIR",
)

DOCKER_CLIENT_ENV_PASSTHROUGH = (
    "DOCKER_CONFIG",
    "DOCKER_CERT_PATH",
    "DOCKER_TLS_VERIFY",
)

SECRET_NAME_PATTERN = re.compile(
    r"TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|_KEY$|^KEY$|APIKEY|PRIVATE",
    re.IGNORECASE,
)
REDACTED = "***"

EXIT_OK = 0
EXIT_OP_FAILED = 1
EXIT_USAGE = 2
EXIT_MUTEX_CONFLICT = 3
EXIT_NOT_FOUND = 4
EXIT_REFUSED = 5
EXIT_EXTERNAL_TOOL = 6
EXIT_INTERRUPTED = 130
